# Base webtop image
ARG BASEIMAGE
FROM ${BASEIMAGE}

# For which architecture to build (amd64 or arm64)
ARG arch

ARG ECLIPSE_RELEASE="2025-06"

# Install Eclipse and the MicroC feature
RUN \
	case ${arch} in \
		arm64) eclipsetgz=eclipse-java-${ECLIPSE_RELEASE}-R-linux-gtk-aarch64.tar.gz ;; \
		amd64) eclipsetgz=eclipse-java-${ECLIPSE_RELEASE}-R-linux-gtk-x86_64.tar.gz ;; \
		*) echo "Unsupported architecture ${arch}" ;; \
	esac ; \
	curl --remote-name "https://mirror.ibcp.fr/pub/eclipse/technology/epp/downloads/release/${ECLIPSE_RELEASE}/R/${eclipsetgz}" ; \
	tar zxf ${eclipsetgz} && rm ${eclipsetgz} ; \
	mv eclipse /usr/local/eclipse_microc

RUN \
	for feature in \
		"org.eclipse.xtext" \
		"org.eclipse.xtext.ui" \
		"org.eclipse.xtext.ui.shared" \
		"org.eclipse.xtext.ui.codetemplates.ui" \
		"org.eclipse.xtext.ide" \
		"org.eclipse.xtext.xbase" \
		"org.eclipse.xtext.xbase.ide" \
		"org.eclipse.ocl" \
		"org.eclipse.ocl.ecore" \
		"org.eclipse.acceleo.model" \
		"org.eclipse.acceleo.engine" ; \
	do /usr/local/eclipse_microc/eclipse -nosplash \
			-application org.eclipse.equinox.p2.director \
			-repository https://download.eclipse.org/releases/${ECLIPSE_RELEASE}/ \
			-installIU "${feature}" ; \
	done

RUN \
	/usr/local/eclipse_microc/eclipse -nosplash \
			-application org.eclipse.equinox.p2.director \
			-repository https://wdi.centralesupelec.fr/boulanger/misc/microc-update-site \
			-installIU "fr.centralesupelec.infonum.sl.microcfeature.feature.group"

# COPY mydocker_startup/wrapper_script.sh /usr/local/lib/wrapper_script.sh

RUN mkdir -p /init-config/init

COPY init-config-eclipse-microc/init/* /init-config/init

RUN \
	cd /init-config/init ; \
	for script in *.sh ; \
	do \
		chmod +x $script ; \
		./$script ; \
	done ; \
	cd .. ; rm -r init

# Clean up
RUN apt-get autoremove && apt-get autoclean && apt-get clean ; \
		rm -rf \
    /tmp/* \
    /config/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

ENTRYPOINT ["/bin/bash", "/usr/local/lib/wrapper_script.sh"]
