FROM lscr.io/linuxserver/webtop:ubuntu-icewm

# For which architecture to build (amd64 or arm64)
ARG arch

ENV HOME="/config"
ENV TZ=Europe/Paris
ARG DEBIAN_FRONTEND=noninteractive

RUN  \
	apt-get update ; \
	apt-get upgrade -y ; \
	apt-get autoclean ; \
	apt-get autoremove ; \
	apt-get install -y \
		libwebkit2gtk-4.1-0

RUN \
  apt-get clean ; \
  rm -rf \
    /tmp/* \
    /config/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

# Install Eclipse and the required features/plugins
RUN \
	case ${arch} in \
		arm64) eclipsetgz=eclipse-modeling-2023-09-R-linux-gtk-aarch64.tar.gz ;; \
		amd64) eclipsetgz=eclipse-modeling-2023-09-R-linux-gtk-x86_64.tar.gz ;; \
		*) echo "Unsupported architecture ${arch}" ;; \
	esac ; \
	curl --remote-name "https://rhlx01.hs-esslingen.de/pub/Mirrors/eclipse/technology/epp/downloads/release/2023-09/R/${eclipsetgz}" ; \
	tar zxf ${eclipsetgz} && rm ${eclipsetgz} ; \
	mv eclipse /usr/local/eclipse ; \
	for feature in \
		"org.eclipse.acceleo.feature.group" \
		"org.eclipse.ocl.examples.feature.group" \
		"org.eclipse.m2m.qvt.oml.tools.coverage.feature.group" \
		"org.eclipse.m2m.qvt.oml.tools.coverage.source.feature.group" \
		"org.eclipse.m2m.qvt.oml.sdk.feature.group" \
		"org.eclipse.m2m.qvt.oml.sdk.source.feature.group" \
		"org.eclipse.xtext.sdk.feature.group" \
		"org.eclipse.cdt.feature.group" \
		"org.eclipse.linuxtools.cdt.libhover.feature.feature.group" \
		"org.eclipse.cdt.testsrunner.feature.feature.group" \
		"org.eclipse.wst.xml_ui.feature.feature.group" \
		"org.eclipse.wst.jsdt.feature.feature.group" \
		"org.eclipse.wildwebdeveloper.feature.feature.group" \
		"org.eclipse.xtend.sdk.feature.group" \
		"org.eclipse.wst.xsl.feature.feature.group" ; \
	do /usr/local/eclipse/eclipse -nosplash \
			-application org.eclipse.equinox.p2.director \
			-repository https://download.eclipse.org/releases/2023-09/ \
			-installIU "${feature}" ; \
	done

# Install MiniARM assembler plugin
RUN /usr/local/eclipse/eclipse -nosplash \
			-application org.eclipse.equinox.p2.director \
			-repository https://wdi.centralesupelec.fr/boulanger/misc/mini-arm-update-site \
			-installIU "fr.centralesupelec.infonum.sl.miniarm.feature.feature.group"

COPY mydocker_startup/wrapper_script.sh /usr/local/lib/wrapper_script.sh

COPY init-config-eclipse/* /init-config/

RUN \
	cd /init-config ; \
	for script in *.sh ; \
	do \
		chmod +x $script ; \
		./$script ; \
		rm $script ; \
	done

ENTRYPOINT ["/bin/bash", "/usr/local/lib/wrapper_script.sh"]
