FROM lscr.io/linuxserver/webtop:ubuntu-icewm

# For which architecture to build (amd64 or arm64)
ARG arch

ENV HOME="/config"
ENV TZ=Europe/Paris
ARG DEBIAN_FRONTEND=noninteractive

# Install Isabelle
RUN \
	isabelle="Isabelle2024"
	case ${arch} in \
		arm64) isabelletgz=${isabelle}_linux_arm.tar.gz ;; \
		amd64) isabelletgz=${isabelle}_linux.tar.gz ;; \
		*) echo "Unsupported architecture ${arch}" ;; \
	esac ; \
	curl --remote-name "https://isabelle.in.tum.de/dist/${isabelletgz}" ; \
	tar zxf ${isabelletgz} && rm ${isabelletgz} ; \
	mv ${isabelle} /usr/local/Isabelle ; \
	ln -s /usr/local/Isabelle/bin/isabelle /usr/local/bin/isabelle

RUN  \
	apt-get update ; \
	apt-get upgrade -y

RUN \
	apt-get install -y \
	make ocaml menhir libnum-ocaml-dev libmenhir-ocaml-dev libzarith-ocaml-dev \
	libzip-ocaml-dev liblablgtk3-ocaml-dev liblablgtksourceview3-ocaml-dev \
	libocamlgraph-ocaml-dev libre-ocaml-dev libjs-of-ocaml-dev alt-ergo z3 cvc4 \
	yaru-theme-icon \
	adwaita-icon-theme-full \
	coqide

RUN \
	why="why3-1.7.2"
	curl -O https://why3.gitlabpages.inria.fr/releases/${why}.tar.gz ; \
	tar zxf ${why}.tar.gz && rm ${why}.tar.gz ; \
	cd ${why} ; \
	./configure ; \
	make ; \
	echo "/usr/local/lib/why3/isabelle" >> /usr/local/Isabelle/etc/components ; \
	make install ; \
	make byte ; \
	make install-lib ; \
	heapsdir=`ls -d /usr/local/Isabelle*/heaps/polyml-*`; \
	homeheaps=`ls -d ${HOME}/.isabelle/Isabelle*/heaps/polyml-*`; \
	mv ${homeheaps}/Why3 ${heapsdir}/ ; \
  mv ${homeheaps}/log/* ${heapsdir}/log/

RUN \
  apt-get clean ; \
  rm -rf \
    /tmp/* \
    /config/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

COPY mydocker_startup/wrapper_script.sh /usr/local/lib/wrapper_script.sh

COPY init-config-isabelle/* /init-config/

RUN \
	cd /init-config ; \
	for script in *.sh ; \
	do \
		chmod +x $script ; \
		./$script ; \
		rm $script ; \
	done

ENTRYPOINT ["/bin/bash", "/usr/local/lib/wrapper_script.sh"]
