# For which architecture to build (amd64 or arm64)
ARG arch

FROM lscr.io/linuxserver/webtop:ubuntu-icewm

ENV HOME="/config"
ENV TZ=Europe/Paris
ENV LIBGL_ALWAYS_SOFTWARE=1

ARG DEBIAN_FRONTEND=noninteractive

# Update apt base
RUN \
	apt-get update ; \
	apt-get upgrade -y ;

# Infrastructure
RUN \
	apt-get install -y \
		yaru-theme-icon \
		adwaita-icon-theme-full \
		at-spi2-core \
		mesa-utils \
		libgl1-mesa-dri \
		libwebkit2gtk-4.1-0

# Basic tools
RUN \
	apt-get install -y \
		nano \
		featherpad \
		pcmanfm \
		lxterminal \
		zip \
		unzip

# Basic dev stuff
RUN \
	apt-get install -y \
		make \
		g++ \
		git \
		libncurses-dev \
		zlib1g-dev \
		libsqlite3-dev \
		sqlite3

RUN \
	apt-get autoremove ; \
	apt-get autoclean ; \
	apt-get clean ; \
	rm -rf \
    /tmp/* \
    /config/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

COPY mydocker_startup/wrapper_script.sh /usr/local/lib/wrapper_script.sh

COPY init-config/* /init-config/

RUN \
	cd /init-config ; \
	for script in *.sh ; \
	do \
		chmod +x $script ; \
		./$script ; \
		rm $script ; \
	done

# Clean up
RUN apt-get autoremove && apt-get autoclean && apt-get clean ; \
		rm -rf \
    /tmp/* \
    /config/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

ENTRYPOINT ["/bin/bash", "/usr/local/lib/wrapper_script.sh"]
