# Base webtop image
ARG BASEIMAGE
FROM ${BASEIMAGE}

# For which architecture to build (amd64 or arm64)
ARG arch

ENV HOME="/config"
ENV TZ=Europe/Paris
ARG DEBIAN_FRONTEND=noninteractive

ARG ATELIERB_YEAR="2024/09"
ARG ATELIERB_RELEASE="atelierb-cssp-24.04"
ARG ATELIERB_PLATFORM="ubuntu-24.04"

ARG ATELIERB_DEB=${ATELIERB_RELEASE}-${ATELIERB_PLATFORM}.deb

# AtelierB CSP Educational version
RUN \
	case ${arch} in \
		arm64) echo "# Error: architecture arm64 is not supported by AtelierB"; exit 1 ;; \
		amd64) echo "Installing ${ATELIERB_DEB}" ;; \
		*) echo "Unsupported architecture ${arch}"; exit 1 ;; \
	esac ; \
	curl --remote-name "https://www.atelierb.eu/wp-content/uploads/${ATELIERB_YEAR}/${ATELIERB_DEB}" ;
	
# Install dependencies
RUN \
		apt update; \
		apt install -y \
			cmake \
			python3-full \
			python3-tk \
			python3-pip \
			qml-module-qtmultimedia \
			qml-module-qtquick-controls2 \
			qml-module-qtquick-controls \
			qtquickcontrols2-5-dev \
			qml-module-qtquick-dialogs \
			qml-module-qtquick-extras \
			qtdeclarative5-dev \
			lib32gcc-s1 \
			lib32stdc++6 \
			libc6-i386 \
			libqt5serialport5 \
			libqt5xmlpatterns5

# Install AtelierB package
RUN \
	dpkg -i ${ATELIERB_DEB}; \
	sed -e 's@^Exec=.*$@Exec=/opt/'${ATELIERB_RELEASE}'/bin/AtelierB@' \
	    -e '/^Categories=.*$/d' \
		/opt/${ATELIERB_RELEASE}/bin/AtelierB.desktop \
			> /usr/share/applications/AtelierB.desktop ; \
		echo "Categories=Proof;Development;Science;Math" \
			>> /usr/share/applications/AtelierB.desktop

RUN mkdir -p /init-config/init
COPY init-config-atelierb/init/* /init-config/init

RUN \
	cd /init-config/init ; \
	for script in *.sh ; \
	do \
		chmod +x $script ; \
		./$script ; \
	done ; \
	cd .. ; rm -r init

# Clean up
RUN apt-get autoremove && apt-get autoclean && apt-get clean ; \
		rm -rf \
    /tmp/* \
    /config/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

ENTRYPOINT ["/bin/bash", "/usr/local/lib/wrapper_script.sh"]
