mkdir -p /init-config/.icewm

cat - > /init-config/.bashrc << "==END=="
/usr/bin/icewmbg
==END==
chmod +x /init-config/.bashrc

cat - > /init-config/.icewm/preferences << "==END=="
ConfirmLogout=1
TimeFormat="%T"
TerminalCommand="uxterm"
LogoutCommand="sudo kill 1"
==END==

cat - > /init-config/.icewm/prefoverride << "==END=="
DesktopBackgroundCenter=1
DesktopBackgroundScaled=0
DesktopBackgroundImage=~/desktop-background.png
DesktopBackgroundColor=black
==END==

# If "menu" is not created empty, a default one is generated by icewm from the installed applications
cat - > /init-config/.icewm/menu << "==END=="
==END==

cat - > /init-config/.icewm/programs << "==END=="
prog "Firefox Web Browser" firefox firefox
prog "ROX Filer" system-file-manager /usr/bin/rox-filer
prog "FeatherPad" featherpad featherpad
prog "UXTerm" mini.xterm uxterm
==END==

cat - > /init-config/.icewm/toolbar << "==END=="
prog "Terminal" mini.xterm /usr/bin/uxterm
prog "FeatherPad" featherpad featherpad
prog "Firefox" firefox /usr/bin/firefox
prog "File browser (Rox)" /usr/share/rox/images/application.png /usr/bin/rox-filer
==END==

cat - > /init-config/.icewm/startup << "==END=="
/usr/bin/icewmbg
==END==

cat - > /init-config/.icewm/theme << "==END=="
Theme="motif/default.theme"
==END==
