mkdir -p /init-config/.icewm

cat - > /init-config/.bashrc << "==END=="
/usr/bin/icewmbg

# Fix "MESA: error: ZINK: failed to choose pdev"
export LIBGL_ALWAYS_SOFTWARE=1

# Set base directory for XDG files
export XDG_RUNTIME_DIR='/config'

# Fix spurious Gtk error messages about accessibility bus
export NO_AT_BRIDGE=1
==END==
chmod +x /init-config/.bashrc

cat - > /init-config/.icewm/preferences << "==END=="
ConfirmLogout=1
TimeFormat="%T"
TerminalCommand="lxterminal"
LogoutCommand="sudo kill 1"
==END==

cat - > /init-config/.icewm/prefoverride << "==END=="
DesktopBackgroundCenter=1
DesktopBackgroundScaled=0
DesktopBackgroundImage=~/desktop-background.png
DesktopBackgroundColor=black
==END==

# If "menu" is not created empty, a default one is generated by icewm from the installed applications
cat - > /init-config/.icewm/menu << "==END=="
==END==

# prog "ROX Filer" system-file-manager /usr/bin/rox-filer
# prog "Eclipse MicroC" /usr/local/eclipse_microc/microc.xpm /usr/local/eclipse_microc/eclipse
cat - > /init-config/.icewm/programs << "==END=="
prog "Firefox Web Browser" firefox firefox
prog "PCMan file manager" system-file-manager /usr/bin/pcmanfm
prog "Eclipse MicroC" /usr/local/eclipse_microc/microc.xpm /usr/local/eclipse_microc/eclipse
prog "FeatherPad" featherpad featherpad
prog "LXTerminal" lxterminal lxterminal
==END==

# prog "File browser (Rox)" /usr/share/rox/images/application.png /usr/bin/rox-filer
# prog "Eclipse MicroC" /usr/local/eclipse_microc/microc.xpm /usr/local/eclipse_microc/eclipse
cat - > /init-config/.icewm/toolbar << "==END=="
prog "Terminal" lxterminal /usr/bin/lxterminal
prog "FeatherPad" featherpad featherpad
prog "Firefox" firefox /usr/bin/firefox
prog "File browser (PCMan)" /usr/share/icons/Humanity/apps/32/system-file-manager.svg /usr/bin/pcmanfm
prog "Eclipse MicroC" /usr/local/eclipse_microc/microc.xpm /usr/local/eclipse_microc/eclipse
==END==

cat - > /init-config/.icewm/startup << "==END=="
/usr/bin/icewmbg
==END==

cat - > /init-config/.icewm/theme << "==END=="
Theme="motif/default.theme"
==END==
